### PR TITLE
Swap testing vs non-testing servlet response

### LINKED ISSUE #2: Is GuestbookServlet "testing" test reversed?
In GuestbookServlet goGet() method it has:
if (req.getParameter("testing") == null) {
    resp.setContentType("text/plain");
    resp.getWriter().println("Hello, this is a testing servlet. \n\n");

Is the what you want or did you mean (req.getParameter("testing") != null)

### PR DESCRIPTION
**Pull request by ajkannan**
Fixes #2.

### CODE REVIEW

**Comment by lesv** [comment]
LGTM - I'm going to wait to merge this 'until later this afternoon when I can test & deploy it.  
@tmatsuo if you wish to do this, I'm ok w/ it.

**Comment by ajkannan** [comment]
Friendly ping on this PR

**Comment by tmatsuo** [comment]
LGTM

**Comment by lesv** [comment]
Takashi - did you also release it to maven central?

**Pull request merged**
